package com.mission21.systemdesign.urlshortener.util;

public class Base62Util {

    private static char [] BASE62_DICTIONARY = new char[]{'0','1','2','3','4','5','6','7','8','9','a','b','c','d','e',
            'f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F',
            'G','H','I','J','K','L','M','N','O','P','R','S','T','U','V','W','X','Y','Z'};
    private static final int BASE = BASE62_DICTIONARY.length;
    private static final int BASE_DECIMAL = 10;

    /**
     *
     * @param number - Random number generated by token service, minimum number generated would be 10^7
     * @return String of length 7 having base 62 characters.
     */
    public static String convertNumberIntoBase62(int number){
        StringBuilder sb = new StringBuilder();
        while (number > 0){
            int remainder = number % BASE;
            number = number/BASE_DECIMAL;
            sb.append(BASE62_DICTIONARY[remainder]);
        }
        return sb.toString();
    }
}
